import type {
  Project,
  Certificate,
  TechItem,
  Stat,
  Profile,
} from "../data/portfolio.types";

function fileHeader(lang: string, exportName: string): string {
  const date = new Date().toISOString().split("T")[0];
  return `// Generated by Portfolio Admin — ${date}
// Replace the '${exportName}' const in src/data/portfolio.${lang}.ts
`;
}

function trigger(filename: string, content: string): void {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadProjectsTs(
  projects: Project[],
  lang: "en" | "vi",
): void {
  const content =
    fileHeader(lang, "projects") +
    `import type { Project } from "./portfolio.types";\n\n` +
    `export const projects: Project[] = ${JSON.stringify(projects, null, 2)};\n`;
  trigger(`projects.${lang}.ts`, content);
}

export function downloadCertificatesTs(certificates: Certificate[]): void {
  const content =
    fileHeader("en", "certificates") +
    `import type { Certificate } from "./portfolio.types";\n\n` +
    `export const certificates: Certificate[] = ${JSON.stringify(certificates, null, 2)};\n`;
  trigger("certificates.ts", content);
}

export function downloadTechStackTs(techStack: TechItem[]): void {
  const content =
    fileHeader("en", "techStack") +
    `import type { TechItem } from "./portfolio.types";\n\n` +
    `export const techStack: TechItem[] = ${JSON.stringify(techStack, null, 2)};\n`;
  trigger("techStack.ts", content);
}

export function downloadStatsTs(stats: Stat[]): void {
  const content =
    fileHeader("en", "stats") +
    `import type { Stat } from "./portfolio.types";\n\n` +
    `export const stats: Stat[] = ${JSON.stringify(stats, null, 2)};\n`;
  trigger("stats.ts", content);
}

export function downloadProfileTs(profile: Profile, lang: "en" | "vi"): void {
  const content =
    fileHeader(lang, "profile") +
    `import type { Profile } from "./portfolio.types";\n\n` +
    `export const profile: Profile = ${JSON.stringify(profile, null, 2)};\n`;
  trigger(`profile.${lang}.ts`, content);
}
